# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DATABASE: $DB_NAME
      POSTGRES_USER: $DB_USER
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  node:
    image: "node"
    build:
      context: ./
      dockerfile: node-dockerfile
    environment:
      APP_ID: $APP_KEY
    ports:
      - 3333:3333
    volumes:
        - .:/usr/app
    depends_on:
      - db
    entrypoint: /usr/app/entrypoint.sh
volumes:
  db-data:
    driver: local
